import Head from "next/head";
import { useState } from "react";

import { Button } from "~/components/ui/button";

export default function Home() {
  const [display, setDisplay] = useState("");
  const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  function hasNumber(myString: string) {
    return /\d/.test(myString);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main
        onKeyDown={(event) => {
          if (hasNumber(event.key)) {
            return setDisplay((prev) => prev + String(event.key));
          }
          if (event.key === "Backspace") {
            return setDisplay((prev) => prev.substring(0, prev.length - 1));
          }
        }}
        className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-t from-[#ddb4f6] to-[#8dd0fc]"
      >
        <div className="flex flex-col gap-5">
          <div className="h-8 w-auto rounded-md bg-slate-100 px-3 py-1 text-right">
            {Number(display).toLocaleString()}
          </div>
          <div className="grid grid-cols-3 gap-3">
            {numbers.reverse().map((val) => (
              <Button
                onClick={() => setDisplay((prev) => prev + String(val))}
                key={val}
                variant={"default"}
                size={"lg"}
              >
                {val}
              </Button>
            ))}
            <Button
              variant={"default"}
              size={"lg"}
              onClick={() =>
                setDisplay((prev) => prev.substring(0, prev.length - 1))
              }
            >
              x
            </Button>
            <Button
              variant={"default"}
              size={"lg"}
              onClick={() => setDisplay((prev) => prev + "0")}
            >
              0
            </Button>
            <Button variant={"default"} size={"lg"}>
              .
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}
