import Head from "next/head";
import { useState } from "react";

import { Button } from "~/components/ui/button";

export default function Home() {
  const [display, setDisplay] = useState("");
  const numbers = [0, "", 1, 2, 3, 4, 5, 6, 7, 8, 9];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-t from-[#ddb4f6] to-[#8dd0fc]">
        <div className="h-6 w-auto bg-slate-100">{display}</div>
        <div className="grid grid-cols-3 gap-3">
          {numbers.reverse().map((val) => (
            <Button onClick={() => setDisplay(String(val))} key={val} variant={"default"} size={"lg"}>
              {val}
            </Button>
          ))}
          <Button variant={"default"} size={"lg"}>
            .
          </Button>
        </div>
      </main>
    </>
  );
}
